<?php
/**
 * Server-side render for the Group Directory block.
 *
 * Renders the initial list of groups from the REST API so the page is
 * usable without JavaScript. The view script hydrates the container for
 * interactive search and pagination.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

$per_page = ! empty( $attributes['perPage'] ) ? absint( $attributes['perPage'] ) : 12;

// Query groups from the main site using the same logic as the REST controller.
$main_site_id = get_main_site_id();
switch_to_blog( $main_site_id );

$query = new WP_Query( [
	'post_type'      => 'wp_meetup',
	'posts_per_page' => $per_page,
	'paged'          => 1,
	'orderby'        => 'title',
	'order'          => 'ASC',
	'post_status'    => 'meetup-active',
] );

$groups      = [];
$total       = (int) $query->found_posts;
$total_pages = (int) $query->max_num_pages;

foreach ( $query->posts as $post ) {
	$site_id = get_post_meta( $post->ID, '_meetup_site_id', true );
	$site_url = '';

	if ( $site_id ) {
		$blog_details = get_blog_details( (int) $site_id );
		if ( $blog_details ) {
			$site_url = esc_url( $blog_details->siteurl );
		}
	}

	$groups[] = [
		'id'           => (int) $post->ID,
		'name'         => esc_html( $post->post_title ),
		'city'         => sanitize_text_field( get_post_meta( $post->ID, '_meetup_city', true ) ),
		'country'      => sanitize_text_field( get_post_meta( $post->ID, '_meetup_country', true ) ),
		'latitude'     => (float) get_post_meta( $post->ID, '_meetup_latitude', true ),
		'longitude'    => (float) get_post_meta( $post->ID, '_meetup_longitude', true ),
		'member_count' => absint( get_post_meta( $post->ID, '_meetup_member_count', true ) ),
		'site_url'     => $site_url,
	];
}

restore_current_blog();

// Build a JSON array of groups with valid coordinates for the map view.
$map_groups = [];
foreach ( $groups as $group ) {
	if ( ! empty( $group['latitude'] ) && ! empty( $group['longitude'] ) ) {
		$map_groups[] = [
			'id'        => $group['id'],
			'name'      => $group['name'],
			'city'      => $group['city'],
			'country'   => $group['country'],
			'latitude'  => $group['latitude'],
			'longitude' => $group['longitude'],
			'site_url'  => $group['site_url'],
		];
	}
}

// Enqueue Leaflet CSS from CDN (same as venue-map block).
wp_enqueue_style(
	'leaflet',
	'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',
	[],
	'1.9.4'
);

// Enqueue Leaflet JS from CDN (same as venue-map block).
wp_enqueue_script(
	'leaflet',
	'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',
	[],
	'1.9.4',
	true
);

$wrapper_attributes = get_block_wrapper_attributes( [
	'class'            => 'wp-block-groups-group-directory',
	'data-per-page'    => $per_page,
	'data-total'       => $total,
	'data-pages'       => $total_pages,
	'data-groups'      => wp_json_encode( $groups ),
	'data-map-groups'  => wp_json_encode( $map_groups ),
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="wp-block-groups-group-directory__search">
		<label for="group-directory-search" class="screen-reader-text">
			<?php esc_html_e( 'Search groups', 'wordpress-groups' ); ?>
		</label>
		<input
			type="search"
			id="group-directory-search"
			class="wp-block-groups-group-directory__search-input"
			placeholder="<?php esc_attr_e( 'Search groups\u2026', 'wordpress-groups' ); ?>"
		/>
	</div>

	<div class="wp-block-groups-group-directory__results" aria-live="polite">
		<?php if ( empty( $groups ) ) : ?>
			<p class="wp-block-groups-group-directory__empty">
				<?php esc_html_e( 'No groups found.', 'wordpress-groups' ); ?>
			</p>
		<?php else : ?>
			<div class="wp-block-groups-group-directory__grid">
				<?php foreach ( $groups as $group ) : ?>
					<article class="wp-block-groups-group-directory__card">
						<h3 class="wp-block-groups-group-directory__card-name">
							<?php if ( $group['site_url'] ) : ?>
								<a href="<?php echo esc_url( $group['site_url'] ); ?>">
									<?php echo esc_html( $group['name'] ); ?>
								</a>
							<?php else : ?>
								<?php echo esc_html( $group['name'] ); ?>
							<?php endif; ?>
						</h3>

						<?php if ( $group['city'] || $group['country'] ) : ?>
							<div class="wp-block-groups-group-directory__card-location">
								<?php
								$location_parts = array_filter( [ $group['city'], $group['country'] ] );
								echo esc_html( implode( ', ', $location_parts ) );
								?>
							</div>
						<?php endif; ?>

						<div class="wp-block-groups-group-directory__card-meta">
							<span class="wp-block-groups-group-directory__card-members">
								<?php
								printf(
									/* translators: %s: Number of members. */
									esc_html( _n( '%s member', '%s members', $group['member_count'], 'wordpress-groups' ) ),
									number_format_i18n( $group['member_count'] )
								);
								?>
							</span>
						</div>
					</article>
				<?php endforeach; ?>
			</div>
		<?php endif; ?>
	</div>

	<?php if ( $total_pages > 1 ) : ?>
		<nav class="wp-block-groups-group-directory__pagination" aria-label="<?php esc_attr_e( 'Group directory pagination', 'wordpress-groups' ); ?>">
			<span class="wp-block-groups-group-directory__page-info">
				<?php
				printf(
					/* translators: 1: Current page, 2: Total pages. */
					esc_html__( 'Page %1$d of %2$d', 'wordpress-groups' ),
					1,
					$total_pages
				);
				?>
			</span>
		</nav>
	<?php endif; ?>
</div>
