<?php
/**
 * Server-side render for the Group Stats block.
 *
 * Displays summary statistic cards for the current group site:
 * total members, past events, upcoming events, total attendees,
 * and next event date.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

/*
 * 1. Total members — count of users on this site.
 */
$member_count = count_users();
$total_members = isset( $member_count['total_users'] ) ? (int) $member_count['total_users'] : 0;

/*
 * 2. Total events held — posts with 'event-past' status.
 */
$past_events_query = new WP_Query( [
	'post_type'              => 'event',
	'post_status'            => 'event-past',
	'posts_per_page'         => 1,
	'no_found_rows'          => false,
	'update_post_meta_cache' => false,
	'update_post_term_cache' => false,
	'fields'                 => 'ids',
] );
$total_past_events = (int) $past_events_query->found_posts;

/*
 * 3. Upcoming events — posts with 'event-scheduled' status.
 */
$upcoming_events_query = new WP_Query( [
	'post_type'              => 'event',
	'post_status'            => 'event-scheduled',
	'posts_per_page'         => 1,
	'no_found_rows'          => false,
	'update_post_meta_cache' => false,
	'update_post_term_cache' => false,
	'fields'                 => 'ids',
] );
$total_upcoming_events = (int) $upcoming_events_query->found_posts;

/*
 * 4. Total attendees — sum of all 'attending' RSVPs across all events.
 */
$total_attendees = (int) get_comments( [
	'post_type'  => 'event',
	'type'       => 'groups_rsvp',
	'status'     => 'approve',
	'meta_key'   => '_rsvp_status',
	'meta_value' => 'attending',
	'count'      => true,
] );

/*
 * 5. Next event date — the earliest scheduled event by start datetime.
 */
$next_event_query = new WP_Query( [
	'post_type'      => 'event',
	'post_status'    => 'event-scheduled',
	'posts_per_page' => 1,
	'meta_key'       => '_event_start_utc',
	'orderby'        => 'meta_value',
	'order'          => 'ASC',
	'fields'         => 'ids',
] );

$next_event_date    = '';
$next_event_display = '';

if ( $next_event_query->posts ) {
	$next_id         = $next_event_query->posts[0];
	$start_utc       = get_post_meta( $next_id, '_event_start_utc', true );
	$event_timezone  = get_post_meta( $next_id, '_event_timezone', true );

	if ( $start_utc ) {
		try {
			$tz = $event_timezone ? new \DateTimeZone( $event_timezone ) : wp_timezone();
		} catch ( \Exception $e ) {
			$tz = wp_timezone();
		}

		$next_event_date    = $start_utc;
		$next_event_display = wp_date( get_option( 'date_format' ), strtotime( $start_utc ), $tz );
	}
}

/*
 * Build the card data.
 */
$cards = [
	[
		'key'   => 'members',
		'icon'  => 'groups',
		'value' => number_format_i18n( $total_members ),
		'label' => __( 'Members', 'wordpress-groups' ),
	],
	[
		'key'   => 'events-held',
		'icon'  => 'calendar',
		'value' => number_format_i18n( $total_past_events ),
		'label' => __( 'Events Held', 'wordpress-groups' ),
	],
	[
		'key'   => 'upcoming',
		'icon'  => 'calendar-alt',
		'value' => number_format_i18n( $total_upcoming_events ),
		'label' => __( 'Upcoming Events', 'wordpress-groups' ),
	],
	[
		'key'   => 'attendees',
		'icon'  => 'yes-alt',
		'value' => number_format_i18n( $total_attendees ),
		'label' => __( 'Total Attendees', 'wordpress-groups' ),
	],
	[
		'key'   => 'next-event',
		'icon'  => 'clock',
		'value' => $next_event_display ? $next_event_display : "\u{2014}",
		'label' => __( 'Next Event', 'wordpress-groups' ),
	],
];

$wrapper_attributes = get_block_wrapper_attributes( [
	'class' => 'wp-block-groups-group-stats',
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?> data-loaded>
	<div class="wp-block-groups-group-stats__loading" role="status">
		<span class="wp-block-groups-group-stats__loading-spinner" aria-hidden="true"></span>
		<?php esc_html_e( 'Loading stats…', 'wordpress-groups' ); ?>
	</div>
	<?php foreach ( $cards as $card ) : ?>
		<div class="wp-block-groups-group-stats__card wp-block-groups-group-stats__card--<?php echo esc_attr( $card['key'] ); ?>">
			<span class="wp-block-groups-group-stats__icon dashicons dashicons-<?php echo esc_attr( $card['icon'] ); ?>" aria-hidden="true"></span>
			<span class="wp-block-groups-group-stats__value">
				<?php
				if ( 'next-event' === $card['key'] && $next_event_date ) {
					printf(
						'<time datetime="%s">%s</time>',
						esc_attr( $next_event_date ),
						esc_html( $card['value'] )
					);
				} else {
					echo esc_html( $card['value'] );
				}
				?>
			</span>
			<span class="wp-block-groups-group-stats__label"><?php echo esc_html( $card['label'] ); ?></span>
		</div>
	<?php endforeach; ?>
</div>
