<?php
/**
 * Server-side render for the Event Date & Time block.
 *
 * Displays the event's date/time in the event's timezone as the primary display,
 * with a <time> element containing a UTC datetime attribute for client-side
 * local time conversion.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

// Determine which event to display: explicit attribute or current post context.
$event_id = ! empty( $attributes['eventId'] )
	? (int) $attributes['eventId']
	: ( $block->context['postId'] ?? 0 );

if ( ! $event_id ) {
	return;
}

$event = get_post( $event_id );

if ( ! $event || 'event' !== $event->post_type ) {
	return;
}

// Event meta.
$start_utc = get_post_meta( $event_id, '_event_start_utc', true );
$end_utc   = get_post_meta( $event_id, '_event_end_utc', true );
$timezone  = get_post_meta( $event_id, '_event_timezone', true );

if ( ! $start_utc ) {
	return;
}

// Resolve timezone with safety fallback.
try {
	$tz = $timezone ? new \DateTimeZone( $timezone ) : wp_timezone();
} catch ( \Exception $e ) {
	$tz = wp_timezone();
}

$start_timestamp = strtotime( $start_utc );
$end_timestamp   = $end_utc ? strtotime( $end_utc ) : 0;

if ( ! $start_timestamp ) {
	return;
}

// Determine the timezone abbreviation for display.
$tz_name = $timezone ? wp_date( 'T', $start_timestamp, $tz ) : '';

// Format the ISO 8601 datetime for the <time> element (always UTC).
$start_iso = gmdate( 'Y-m-d\TH:i:s\Z', $start_timestamp );
$end_iso   = $end_timestamp ? gmdate( 'Y-m-d\TH:i:s\Z', $end_timestamp ) : '';

// Check if this is a multi-day event.
$start_date_local = wp_date( 'Y-m-d', $start_timestamp, $tz );
$end_date_local   = $end_timestamp ? wp_date( 'Y-m-d', $end_timestamp, $tz ) : '';
$is_multi_day     = $end_date_local && $start_date_local !== $end_date_local;

// Build date/time display strings.
$date_format = get_option( 'date_format' );
$time_format = get_option( 'time_format' );

if ( $is_multi_day ) {
	// Multi-day: "January 15, 2025 at 7:00 PM – January 17, 2025 at 10:00 PM EST".
	$start_display = wp_date( $date_format, $start_timestamp, $tz )
		. ' ' . __( 'at', 'wordpress-groups' ) . ' '
		. wp_date( $time_format, $start_timestamp, $tz );

	$end_display = wp_date( $date_format, $end_timestamp, $tz )
		. ' ' . __( 'at', 'wordpress-groups' ) . ' '
		. wp_date( $time_format, $end_timestamp, $tz );

	$datetime_display = $start_display . ' – ' . $end_display;
} else {
	// Single day: date on one line, time range on another.
	$date_display = wp_date( $date_format, $start_timestamp, $tz );
	$time_display = wp_date( $time_format, $start_timestamp, $tz );

	if ( $end_timestamp ) {
		$time_display .= ' – ' . wp_date( $time_format, $end_timestamp, $tz );
	}

	$datetime_display = '';
}

// Append timezone abbreviation.
if ( $tz_name ) {
	if ( $is_multi_day ) {
		$datetime_display .= ' ' . $tz_name;
	} else {
		$time_display .= ' ' . $tz_name;
	}
}

$wrapper_attributes = get_block_wrapper_attributes( [
	'class' => 'wp-block-groups-event-datetime',
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="wp-block-groups-event-datetime__primary">
		<?php if ( $is_multi_day ) : ?>
			<time
				class="wp-block-groups-event-datetime__range"
				datetime="<?php echo esc_attr( $start_iso ); ?>"
				data-utc-start="<?php echo esc_attr( $start_iso ); ?>"
				data-utc-end="<?php echo esc_attr( $end_iso ); ?>"
			>
				<?php echo esc_html( $datetime_display ); ?>
			</time>
		<?php else : ?>
			<time
				class="wp-block-groups-event-datetime__date"
				datetime="<?php echo esc_attr( $start_iso ); ?>"
				data-utc-start="<?php echo esc_attr( $start_iso ); ?>"
				<?php if ( $end_iso ) : ?>
					data-utc-end="<?php echo esc_attr( $end_iso ); ?>"
				<?php endif; ?>
			>
				<span class="wp-block-groups-event-datetime__date-text">
					<?php echo esc_html( $date_display ); ?>
				</span>
				<span class="wp-block-groups-event-datetime__time-text">
					<?php echo esc_html( $time_display ); ?>
				</span>
			</time>
		<?php endif; ?>
	</div>

	<div class="wp-block-groups-event-datetime__local" aria-live="polite" hidden>
		<?php /* Populated by view.js with the viewer's local time. */ ?>
	</div>
</div>
