<?php
/**
 * Server-side render for the Group Members block.
 *
 * Displays site members grouped by role (organizer, co_organizer, member)
 * in a responsive grid with avatars and role badges.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

$per_page = ! empty( $attributes['perPage'] ) ? absint( $attributes['perPage'] ) : 50;
$page     = ! empty( $attributes['page'] ) ? absint( $attributes['page'] ) : 1;
$offset   = ( $page - 1 ) * $per_page;

// Role definitions: slug => label, ordered by display priority.
$roles = [
	'organizer'    => __( 'Organizer', 'wordpress-groups' ),
	'co_organizer' => __( 'Co-Organizer', 'wordpress-groups' ),
	'member'       => __( 'Member', 'wordpress-groups' ),
];

$blog_id = get_current_blog_id();

// Fetch all users for this site with the relevant roles.
$all_users = get_users( [
	'blog_id' => $blog_id,
	'role__in' => array_keys( $roles ),
	'orderby' => 'display_name',
	'order'   => 'ASC',
] );

if ( empty( $all_users ) ) {
	return;
}

// Group users by their role, respecting role priority order.
$grouped = [];
foreach ( array_keys( $roles ) as $role ) {
	$grouped[ $role ] = [];
}

foreach ( $all_users as $user ) {
	// Assign each user to their highest-priority matching role.
	foreach ( array_keys( $roles ) as $role ) {
		if ( in_array( $role, $user->roles, true ) ) {
			$grouped[ $role ][] = $user;
			break;
		}
	}
}

// Build flat list in role order for pagination.
$ordered_users = [];
foreach ( array_keys( $roles ) as $role ) {
	foreach ( $grouped[ $role ] as $user ) {
		$ordered_users[] = [
			'user' => $user,
			'role' => $role,
		];
	}
}

$total_users = count( $ordered_users );
$total_pages = (int) ceil( $total_users / $per_page );

// Slice for current page.
$paged_users = array_slice( $ordered_users, $offset, $per_page );

if ( empty( $paged_users ) ) {
	return;
}

// Group the paged results by role for section rendering.
$sections = [];
foreach ( $paged_users as $entry ) {
	$role = $entry['role'];
	if ( ! isset( $sections[ $role ] ) ) {
		$sections[ $role ] = [];
	}
	$sections[ $role ][] = $entry['user'];
}

$wrapper_attributes = get_block_wrapper_attributes( [
	'class' => 'wp-block-groups-group-members',
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<?php foreach ( $sections as $role => $users ) : ?>
		<section class="wp-block-groups-group-members__section" aria-label="<?php echo esc_attr( $roles[ $role ] ); ?>">
			<h3 class="wp-block-groups-group-members__role-heading">
				<?php
				printf(
					/* translators: 1: Role name, 2: Number of users with that role. */
					esc_html__( '%1$s (%2$d)', 'wordpress-groups' ),
					esc_html( $roles[ $role ] ),
					count( $grouped[ $role ] )
				);
				?>
			</h3>

			<ul class="wp-block-groups-group-members__grid" role="list">
				<?php foreach ( $users as $user ) : ?>
					<li class="wp-block-groups-group-members__member">
						<div class="wp-block-groups-group-members__avatar">
							<?php echo get_avatar( $user->ID, 80, '', esc_attr( $user->display_name ) ); ?>
						</div>
						<div class="wp-block-groups-group-members__info">
							<span class="wp-block-groups-group-members__name">
								<?php echo esc_html( $user->display_name ); ?>
							</span>
							<span class="wp-block-groups-group-members__badge wp-block-groups-group-members__badge--<?php echo esc_attr( sanitize_html_class( $role ) ); ?>">
								<?php echo esc_html( $roles[ $role ] ); ?>
							</span>
						</div>
					</li>
				<?php endforeach; ?>
			</ul>
		</section>
	<?php endforeach; ?>

	<?php if ( $total_pages > 1 ) : ?>
		<nav class="wp-block-groups-group-members__pagination" aria-label="<?php esc_attr_e( 'Member list pagination', 'wordpress-groups' ); ?>">
			<?php if ( $page > 1 ) : ?>
				<span class="wp-block-groups-group-members__pagination-prev">
					<?php
					printf(
						'<a href="%s">%s</a>',
						esc_url( add_query_arg( 'members_page', $page - 1 ) ),
						esc_html__( 'Previous', 'wordpress-groups' )
					);
					?>
				</span>
			<?php endif; ?>

			<span class="wp-block-groups-group-members__pagination-current">
				<?php
				printf(
					/* translators: 1: Current page, 2: Total pages. */
					esc_html__( 'Page %1$d of %2$d', 'wordpress-groups' ),
					$page,
					$total_pages
				);
				?>
			</span>

			<?php if ( $page < $total_pages ) : ?>
				<span class="wp-block-groups-group-members__pagination-next">
					<?php
					printf(
						'<a href="%s">%s</a>',
						esc_url( add_query_arg( 'members_page', $page + 1 ) ),
						esc_html__( 'Next', 'wordpress-groups' )
					);
					?>
				</span>
			<?php endif; ?>
		</nav>
	<?php endif; ?>
</div>
