<?php
/**
 * Server-side render for the Organizer Dashboard block.
 *
 * Displays dashboard cards for group organizers: upcoming events,
 * recent RSVPs, member count, and quick action links.
 *
 * Only visible to organizers, co-organizers, and network administrators.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

$current_user_id = get_current_user_id();
$blog_id         = get_current_blog_id();

// Only visible to organizers, co-organizers, and super admins.
if ( ! $current_user_id ) {
	return;
}

$user  = wp_get_current_user();
$roles = (array) $user->roles;

$is_organizer = in_array( 'organizer', $roles, true )
	|| in_array( 'co_organizer', $roles, true )
	|| in_array( 'administrator', $roles, true )
	|| is_super_admin( $current_user_id );

if ( ! $is_organizer ) {
	return;
}

/*
 * 1. Member count — total users on this site.
 */
$member_count  = count_users();
$total_members = isset( $member_count['total_users'] ) ? (int) $member_count['total_users'] : 0;

/*
 * 2. Upcoming events — posts with 'event-scheduled' status.
 */
$upcoming_query = new WP_Query( [
	'post_type'              => 'event',
	'post_status'            => 'event-scheduled',
	'posts_per_page'         => 5,
	'no_found_rows'          => false,
	'update_post_term_cache' => false,
	'meta_key'               => '_event_start_utc',
	'orderby'                => 'meta_value',
	'order'                  => 'ASC',
] );
$total_upcoming = (int) $upcoming_query->found_posts;

/*
 * 3. Recent RSVPs — latest RSVP comments across all events (last 7 days).
 */
$recent_rsvps = get_comments( [
	'post_type'  => 'event',
	'status'     => 'approve',
	'meta_key'   => '_rsvp_status',
	'meta_value' => 'attending',
	'number'     => 5,
	'orderby'    => 'comment_date',
	'order'      => 'DESC',
	'date_query' => [
		[
			'after' => '7 days ago',
		],
	],
] );
$recent_rsvp_count = count( $recent_rsvps );

// Total attending RSVPs across all events.
$total_rsvps = (int) get_comments( [
	'post_type'  => 'event',
	'status'     => 'approve',
	'meta_key'   => '_rsvp_status',
	'meta_value' => 'attending',
	'count'      => true,
] );

/*
 * Build the stat cards.
 */
$cards = [
	[
		'key'   => 'members',
		'icon'  => 'groups',
		'value' => number_format_i18n( $total_members ),
		'label' => __( 'Members', 'wordpress-groups' ),
	],
	[
		'key'   => 'upcoming-events',
		'icon'  => 'calendar-alt',
		'value' => number_format_i18n( $total_upcoming ),
		'label' => __( 'Upcoming Events', 'wordpress-groups' ),
	],
	[
		'key'   => 'recent-rsvps',
		'icon'  => 'yes-alt',
		'value' => number_format_i18n( $recent_rsvp_count ),
		'label' => __( 'RSVPs This Week', 'wordpress-groups' ),
	],
	[
		'key'   => 'total-rsvps',
		'icon'  => 'businessman',
		'value' => number_format_i18n( $total_rsvps ),
		'label' => __( 'Total Attendees', 'wordpress-groups' ),
	],
];

/*
 * Build the upcoming events list.
 */
$upcoming_events = [];
if ( $upcoming_query->have_posts() ) {
	while ( $upcoming_query->have_posts() ) {
		$upcoming_query->the_post();
		$event_id   = get_the_ID();
		$start_utc  = get_post_meta( $event_id, '_event_start_utc', true );
		$timezone   = get_post_meta( $event_id, '_event_timezone', true );

		try {
			$tz = $timezone ? new \DateTimeZone( $timezone ) : wp_timezone();
		} catch ( \Exception $e ) {
			$tz = wp_timezone();
		}

		$rsvp_count = (int) get_comments( [
			'post_id'    => $event_id,
			'status'     => 'approve',
			'meta_key'   => '_rsvp_status',
			'meta_value' => 'attending',
			'count'      => true,
		] );

		$upcoming_events[] = [
			'title'      => get_the_title(),
			'url'        => get_permalink(),
			'date'       => $start_utc ? wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), strtotime( $start_utc ), $tz ) : '',
			'rsvp_count' => $rsvp_count,
		];
	}
	wp_reset_postdata();
}

/*
 * Quick actions.
 */
$quick_actions = [
	[
		'label' => __( 'Create Event', 'wordpress-groups' ),
		'url'   => admin_url( 'post-new.php?post_type=event' ),
		'icon'  => 'plus-alt',
	],
	[
		'label' => __( 'Manage Members', 'wordpress-groups' ),
		'url'   => admin_url( 'users.php' ),
		'icon'  => 'admin-users',
	],
];

$wrapper_attributes = get_block_wrapper_attributes( [
	'class' => 'wp-block-groups-organizer-dashboard',
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<h2 class="wp-block-groups-organizer-dashboard__heading">
		<?php esc_html_e( 'Organizer Dashboard', 'wordpress-groups' ); ?>
	</h2>

	<div class="wp-block-groups-organizer-dashboard__cards">
		<?php foreach ( $cards as $card ) : ?>
			<div class="wp-block-groups-organizer-dashboard__card wp-block-groups-organizer-dashboard__card--<?php echo esc_attr( $card['key'] ); ?>">
				<span class="wp-block-groups-organizer-dashboard__card-icon dashicons dashicons-<?php echo esc_attr( $card['icon'] ); ?>" aria-hidden="true"></span>
				<span class="wp-block-groups-organizer-dashboard__card-value"><?php echo esc_html( $card['value'] ); ?></span>
				<span class="wp-block-groups-organizer-dashboard__card-label"><?php echo esc_html( $card['label'] ); ?></span>
			</div>
		<?php endforeach; ?>
	</div>

	<?php if ( $upcoming_events ) : ?>
		<div class="wp-block-groups-organizer-dashboard__section">
			<h3 class="wp-block-groups-organizer-dashboard__section-title">
				<?php esc_html_e( 'Upcoming Events', 'wordpress-groups' ); ?>
			</h3>
			<ul class="wp-block-groups-organizer-dashboard__event-list">
				<?php foreach ( $upcoming_events as $event ) : ?>
					<li class="wp-block-groups-organizer-dashboard__event-item">
						<a href="<?php echo esc_url( $event['url'] ); ?>" class="wp-block-groups-organizer-dashboard__event-title">
							<?php echo esc_html( $event['title'] ); ?>
						</a>
						<?php if ( $event['date'] ) : ?>
							<span class="wp-block-groups-organizer-dashboard__event-date">
								<?php echo esc_html( $event['date'] ); ?>
							</span>
						<?php endif; ?>
						<span class="wp-block-groups-organizer-dashboard__event-rsvp-count">
							<?php
							printf(
								/* translators: %s: number of attending RSVPs */
								esc_html__( '%s attending', 'wordpress-groups' ),
								esc_html( number_format_i18n( $event['rsvp_count'] ) )
							);
							?>
						</span>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	<?php endif; ?>

	<?php if ( $recent_rsvps ) : ?>
		<div class="wp-block-groups-organizer-dashboard__section">
			<h3 class="wp-block-groups-organizer-dashboard__section-title">
				<?php esc_html_e( 'Recent RSVPs', 'wordpress-groups' ); ?>
			</h3>
			<ul class="wp-block-groups-organizer-dashboard__rsvp-list">
				<?php foreach ( $recent_rsvps as $rsvp ) : ?>
					<li class="wp-block-groups-organizer-dashboard__rsvp-item">
						<?php
						$rsvp_user  = get_user_by( 'id', $rsvp->user_id );
						$event_post = get_post( $rsvp->comment_post_ID );
						if ( $rsvp_user && $event_post ) {
							printf(
								/* translators: 1: user display name, 2: event title */
								esc_html__( '%1$s RSVP\'d to %2$s', 'wordpress-groups' ),
								esc_html( $rsvp_user->display_name ),
								esc_html( $event_post->post_title )
							);
						}
						?>
						<span class="wp-block-groups-organizer-dashboard__rsvp-date">
							<?php echo esc_html( human_time_diff( strtotime( $rsvp->comment_date ), current_time( 'timestamp' ) ) . ' ' . __( 'ago', 'wordpress-groups' ) ); ?>
						</span>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	<?php endif; ?>

	<div class="wp-block-groups-organizer-dashboard__actions">
		<?php foreach ( $quick_actions as $action ) : ?>
			<a href="<?php echo esc_url( $action['url'] ); ?>" class="wp-block-groups-organizer-dashboard__action-link">
				<span class="dashicons dashicons-<?php echo esc_attr( $action['icon'] ); ?>" aria-hidden="true"></span>
				<?php echo esc_html( $action['label'] ); ?>
			</a>
		<?php endforeach; ?>
	</div>
</div>
