<?php
/**
 * Server-side render for the Member Profile block.
 *
 * Displays a member profile card with large avatar, display name, role badge,
 * membership date, events attended count, and upcoming RSVPs.
 *
 * When placed on an author archive, it automatically displays the queried
 * author. Otherwise, a userId attribute can be set explicitly.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

use Groups\Models\Rsvp;

defined( 'ABSPATH' ) || exit;

// Determine which user to display.
$user_id = ! empty( $attributes['userId'] ) ? (int) $attributes['userId'] : 0;

// Fall back to the queried author on author archive pages.
if ( ! $user_id && is_author() ) {
	$user_id = (int) get_queried_object_id();
}

if ( ! $user_id ) {
	return;
}

$user = get_userdata( $user_id );

if ( ! $user ) {
	return;
}

$blog_id = get_current_blog_id();

// Check if the user is a member of this site.
if ( ! is_user_member_of_blog( $user_id, $blog_id ) ) {
	return;
}

// Role definitions for display.
$role_labels = [
	'organizer'    => __( 'Organizer', 'wordpress-groups' ),
	'co_organizer' => __( 'Co-Organizer', 'wordpress-groups' ),
	'member'       => __( 'Member', 'wordpress-groups' ),
];

// Get the user's highest-priority role on this site.
$user_role      = '';
$user_role_label = '';

foreach ( array_keys( $role_labels ) as $role ) {
	if ( in_array( $role, $user->roles, true ) ) {
		$user_role       = $role;
		$user_role_label = $role_labels[ $role ];
		break;
	}
}

// Member since date.
$joined_date   = get_user_meta( $user_id, "_groups_joined_{$blog_id}", true );
$member_since  = '';

if ( $joined_date ) {
	$member_since = wp_date( get_option( 'date_format' ), strtotime( $joined_date ) );
} else {
	// Fall back to user registration date.
	$member_since = wp_date( get_option( 'date_format' ), strtotime( $user->user_registered ) );
}

// Events attended — count RSVPs with attendance confirmed.
$attended_rsvps = get_comments( [
	'user_id'    => $user_id,
	'type'       => Rsvp::COMMENT_TYPE,
	'status'     => 'approve',
	'count'      => true,
	'meta_query' => [ // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
		[
			'key'   => '_rsvp_attendance_confirmed',
			'value' => '1',
		],
	],
] );

$events_attended = (int) $attended_rsvps;

// Upcoming RSVPs — events the user is attending that haven't happened yet.
$upcoming_rsvps = get_comments( [
	'user_id' => $user_id,
	'type'    => Rsvp::COMMENT_TYPE,
	'status'  => 'approve',
	'meta_query' => [ // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
		[
			'key'   => '_rsvp_status',
			'value' => 'attending',
		],
	],
] );

// Filter to only upcoming events.
$upcoming_events = [];
$now             = current_time( 'mysql', true );

foreach ( $upcoming_rsvps as $rsvp_comment ) {
	$event_id  = (int) $rsvp_comment->comment_post_ID;
	$event     = get_post( $event_id );

	if ( ! $event || 'event' !== $event->post_type ) {
		continue;
	}

	$start_utc = get_post_meta( $event_id, '_event_start_utc', true );

	if ( ! $start_utc || $start_utc < $now ) {
		continue;
	}

	$event_timezone = get_post_meta( $event_id, '_event_timezone', true );

	try {
		$tz = $event_timezone ? new \DateTimeZone( $event_timezone ) : wp_timezone();
	} catch ( \Exception $e ) {
		$tz = wp_timezone();
	}

	$upcoming_events[] = [
		'id'    => $event_id,
		'title' => get_the_title( $event_id ),
		'date'  => wp_date( get_option( 'date_format' ), strtotime( $start_utc ), $tz ),
		'url'   => get_permalink( $event_id ),
	];
}

// Sort upcoming events by date ascending.
usort( $upcoming_events, function ( $a, $b ) {
	return strcmp( $a['date'], $b['date'] );
} );

// Limit to 5 upcoming events.
$upcoming_events = array_slice( $upcoming_events, 0, 5 );

$wrapper_attributes = get_block_wrapper_attributes( [
	'class' => 'wp-block-groups-member-profile',
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="wp-block-groups-member-profile__header">
		<div class="wp-block-groups-member-profile__avatar">
			<?php echo get_avatar( $user_id, 150, '', esc_attr( $user->display_name ) ); ?>
		</div>

		<div class="wp-block-groups-member-profile__identity">
			<h2 class="wp-block-groups-member-profile__name">
				<?php echo esc_html( $user->display_name ); ?>
			</h2>

			<?php if ( $user_role_label ) : ?>
				<span class="wp-block-groups-member-profile__badge wp-block-groups-member-profile__badge--<?php echo esc_attr( sanitize_html_class( $user_role ) ); ?>">
					<?php echo esc_html( $user_role_label ); ?>
				</span>
			<?php endif; ?>

			<?php if ( $member_since ) : ?>
				<span class="wp-block-groups-member-profile__joined">
					<?php
					printf(
						/* translators: %s: Date the member joined. */
						esc_html__( 'Member since %s', 'wordpress-groups' ),
						esc_html( $member_since )
					);
					?>
				</span>
			<?php endif; ?>
		</div>
	</div>

	<div class="wp-block-groups-member-profile__stats">
		<div class="wp-block-groups-member-profile__stat">
			<span class="wp-block-groups-member-profile__stat-value">
				<?php echo esc_html( number_format_i18n( $events_attended ) ); ?>
			</span>
			<span class="wp-block-groups-member-profile__stat-label">
				<?php esc_html_e( 'Events Attended', 'wordpress-groups' ); ?>
			</span>
		</div>

		<div class="wp-block-groups-member-profile__stat">
			<span class="wp-block-groups-member-profile__stat-value">
				<?php echo esc_html( number_format_i18n( count( $upcoming_events ) ) ); ?>
			</span>
			<span class="wp-block-groups-member-profile__stat-label">
				<?php esc_html_e( 'Upcoming RSVPs', 'wordpress-groups' ); ?>
			</span>
		</div>
	</div>

	<?php if ( ! empty( $upcoming_events ) ) : ?>
		<div class="wp-block-groups-member-profile__upcoming">
			<h3 class="wp-block-groups-member-profile__upcoming-heading">
				<?php esc_html_e( 'Upcoming Events', 'wordpress-groups' ); ?>
			</h3>

			<ul class="wp-block-groups-member-profile__upcoming-list">
				<?php foreach ( $upcoming_events as $event ) : ?>
					<li class="wp-block-groups-member-profile__upcoming-item">
						<a href="<?php echo esc_url( $event['url'] ); ?>">
							<?php echo esc_html( $event['title'] ); ?>
						</a>
						<time class="wp-block-groups-member-profile__upcoming-date">
							<?php echo esc_html( $event['date'] ); ?>
						</time>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	<?php endif; ?>
</div>
