<?php
/**
 * Server-side render for the Add to Calendar block.
 *
 * Builds Google Calendar, Outlook, and iCal download links from event meta.
 * Uses a CSS-only <details>/<summary> dropdown — no JavaScript needed.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

// Determine which event to display: explicit attribute or current post context.
$event_id = ! empty( $attributes['eventId'] )
	? (int) $attributes['eventId']
	: ( $block->context['postId'] ?? 0 );

if ( ! $event_id ) {
	return;
}

$event = get_post( $event_id );

if ( ! $event || 'event' !== $event->post_type ) {
	return;
}

// Event meta.
$start_utc = get_post_meta( $event_id, '_event_start_utc', true );
$end_utc   = get_post_meta( $event_id, '_event_end_utc', true );
$timezone  = get_post_meta( $event_id, '_event_timezone', true );
$venue_id  = get_post_meta( $event_id, '_event_venue_id', true );

if ( ! $start_utc || ! $end_utc ) {
	return;
}

$title       = $event->post_title;
$description = wp_strip_all_tags( $event->post_content );
$event_url   = get_permalink( $event_id );

// Build location from venue.
$location = '';
if ( $venue_id ) {
	$venue = get_post( (int) $venue_id );
	if ( $venue ) {
		$location = $venue->post_title;
		$address  = get_post_meta( $venue->ID, '_venue_address', true );
		$city     = get_post_meta( $venue->ID, '_venue_city', true );
		if ( $address || $city ) {
			$parts = array_filter( [ $address, $city ] );
			if ( $parts ) {
				$location .= ', ' . implode( ', ', $parts );
			}
		}
	}
}

// Format dates for Google Calendar (UTC, YYYYMMDDTHHmmssZ).
$start_timestamp = strtotime( $start_utc );
$end_timestamp   = strtotime( $end_utc );

if ( ! $start_timestamp || ! $end_timestamp ) {
	return;
}

$gcal_start = gmdate( 'Ymd\THis\Z', $start_timestamp );
$gcal_end   = gmdate( 'Ymd\THis\Z', $end_timestamp );

// Google Calendar URL.
$gcal_params = [
	'action'   => 'TEMPLATE',
	'text'     => $title,
	'dates'    => $gcal_start . '/' . $gcal_end,
	'details'  => $description ? mb_substr( $description, 0, 1024 ) : '',
	'location' => $location,
	'sprop'    => 'website:' . wp_parse_url( home_url(), PHP_URL_HOST ),
];
$gcal_url = 'https://calendar.google.com/calendar/render?' . http_build_query( $gcal_params );

// Outlook.com URL.
$outlook_start = gmdate( 'Y-m-d\TH:i:s\Z', $start_timestamp );
$outlook_end   = gmdate( 'Y-m-d\TH:i:s\Z', $end_timestamp );

$outlook_params = [
	'rru'      => 'addevent',
	'subject'  => $title,
	'startdt'  => $outlook_start,
	'enddt'    => $outlook_end,
	'body'     => $description ? mb_substr( $description, 0, 1024 ) : '',
	'location' => $location,
	'path'     => '/calendar/action/compose',
];
$outlook_url = 'https://outlook.live.com/calendar/0/action/compose?' . http_build_query( $outlook_params );

// iCal download URL (uses the existing ?ical=1 endpoint).
$ical_url = add_query_arg( 'ical', '1', $event_url );

$wrapper_attributes = get_block_wrapper_attributes( [
	'class' => 'wp-block-groups-add-to-calendar',
] );
?>
<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<details class="wp-block-groups-add-to-calendar__dropdown">
		<summary class="wp-block-groups-add-to-calendar__btn">
			<span class="wp-block-groups-add-to-calendar__label">
				<?php esc_html_e( 'Add to Calendar', 'wordpress-groups' ); ?>
			</span>
			<span class="wp-block-groups-add-to-calendar__icon" aria-hidden="true">&#9662;</span>
		</summary>
		<ul class="wp-block-groups-add-to-calendar__menu" role="list">
			<li>
				<a
					class="wp-block-groups-add-to-calendar__link"
					href="<?php echo esc_url( $gcal_url ); ?>"
					target="_blank"
					rel="noopener noreferrer"
				>
					<?php esc_html_e( 'Google Calendar', 'wordpress-groups' ); ?>
				</a>
			</li>
			<li>
				<a
					class="wp-block-groups-add-to-calendar__link"
					href="<?php echo esc_url( $outlook_url ); ?>"
					target="_blank"
					rel="noopener noreferrer"
				>
					<?php esc_html_e( 'Outlook', 'wordpress-groups' ); ?>
				</a>
			</li>
			<li>
				<a
					class="wp-block-groups-add-to-calendar__link"
					href="<?php echo esc_url( $ical_url ); ?>"
					download
				>
					<?php esc_html_e( 'iCal File (.ics)', 'wordpress-groups' ); ?>
				</a>
			</li>
		</ul>
	</details>
</div>
