<?php
/**
 * Server-side render for the Event Directory block.
 *
 * Outputs an initial list of upcoming events and a container for client-side
 * React hydration. The view script takes over for interactivity (filtering,
 * pagination, calendar/list toggle).
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

$per_page = ! empty( $attributes['perPage'] ) ? absint( $attributes['perPage'] ) : 10;

// Query upcoming events for the initial server render.
$query_args = [
	'post_type'      => 'event',
	'posts_per_page' => $per_page,
	'post_status'    => [ 'event-scheduled', 'event-active', 'publish' ],
	'orderby'        => 'meta_value',
	'meta_key'       => '_event_start_utc', // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_key
	'order'          => 'ASC',
	'meta_query'     => [ // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
		[
			'key'     => '_event_start_utc',
			'value'   => gmdate( 'Y-m-d H:i:s' ),
			'compare' => '>=',
			'type'    => 'DATETIME',
		],
	],
];

$events_query = new WP_Query( $query_args );

// Collect categories for the filter dropdown.
$categories = get_categories( [
	'taxonomy'   => 'category',
	'hide_empty' => true,
	'object_ids' => get_posts( [
		'post_type'      => 'event',
		'posts_per_page' => -1,
		'post_status'    => [ 'event-scheduled', 'event-active', 'publish' ],
		'fields'         => 'ids',
	] ),
] );

$category_options = [];
foreach ( $categories as $cat ) {
	$category_options[] = [
		'slug' => $cat->slug,
		'name' => $cat->name,
	];
}

$wrapper_attributes = get_block_wrapper_attributes( [
	'class'           => 'wp-block-groups-event-directory',
	'data-per-page'   => esc_attr( $per_page ),
	'data-categories' => esc_attr( wp_json_encode( $category_options ) ),
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="wp-block-groups-event-directory__server-render">
		<h2 class="wp-block-groups-event-directory__heading">
			<?php esc_html_e( 'Upcoming Events', 'wordpress-groups' ); ?>
		</h2>

		<?php if ( $events_query->have_posts() ) : ?>
			<ul class="wp-block-groups-event-directory__list">
				<?php while ( $events_query->have_posts() ) : ?>
					<?php $events_query->the_post(); ?>
					<?php
					$event_id   = get_the_ID();
					$start_date = get_post_meta( $event_id, '_event_start_utc', true );
					$timezone   = get_post_meta( $event_id, '_event_timezone', true );
					$venue_id   = (int) get_post_meta( $event_id, '_event_venue_id', true );
					$online     = get_post_meta( $event_id, '_event_online_link', true );

					$date_display = '';
					if ( $start_date ) {
						try {
							$tz = $timezone ? new DateTimeZone( $timezone ) : wp_timezone();
						} catch ( Exception $e ) {
							$tz = wp_timezone();
						}
						$date_display = wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), strtotime( $start_date ), $tz );
					}

					$venue_name = '';
					if ( $venue_id ) {
						$venue = get_post( $venue_id );
						if ( $venue && 'venue' === $venue->post_type ) {
							$venue_name = $venue->post_title;
						}
					} elseif ( $online ) {
						$venue_name = __( 'Online', 'wordpress-groups' );
					}
					?>
					<li class="wp-block-groups-event-directory__event-item">
						<a href="<?php the_permalink(); ?>" class="wp-block-groups-event-directory__event-link">
							<?php the_title(); ?>
						</a>
						<?php if ( $date_display ) : ?>
							<span class="wp-block-groups-event-directory__event-date">
								<?php echo esc_html( $date_display ); ?>
							</span>
						<?php endif; ?>
						<?php if ( $venue_name ) : ?>
							<span class="wp-block-groups-event-directory__event-venue">
								<?php echo esc_html( $venue_name ); ?>
							</span>
						<?php endif; ?>
					</li>
				<?php endwhile; ?>
				<?php wp_reset_postdata(); ?>
			</ul>
		<?php else : ?>
			<p class="wp-block-groups-event-directory__empty">
				<?php esc_html_e( 'No upcoming events found.', 'wordpress-groups' ); ?>
			</p>
		<?php endif; ?>
	</div>
</div>
