<?php
/**
 * Server-side render for the Venue Map block.
 *
 * Renders a container div with data attributes for Leaflet initialization,
 * and an accessible text fallback with the venue address.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

// Determine which venue to display: explicit attribute, event's venue, or current post context.
$venue_id = ! empty( $attributes['venueId'] )
	? (int) $attributes['venueId']
	: 0;

// If no explicit venue ID, try to get it from context.
if ( ! $venue_id ) {
	$post_id   = $block->context['postId'] ?? 0;
	$post_type = $block->context['postType'] ?? '';

	if ( $post_id && 'venue' === $post_type ) {
		$venue_id = (int) $post_id;
	} elseif ( $post_id && 'event' === $post_type ) {
		// If we're in an event context, get the linked venue.
		$venue_id = (int) get_post_meta( $post_id, '_event_venue_id', true );
	}
}

if ( ! $venue_id ) {
	return;
}

$venue = get_post( $venue_id );

if ( ! $venue || 'venue' !== $venue->post_type ) {
	return;
}

// Venue meta.
$latitude  = get_post_meta( $venue_id, '_venue_latitude', true );
$longitude = get_post_meta( $venue_id, '_venue_longitude', true );

// Cannot render a map without coordinates.
if ( '' === $latitude || '' === $longitude ) {
	return;
}

$latitude  = (float) $latitude;
$longitude = (float) $longitude;

$venue_name = get_the_title( $venue_id );
$address    = get_post_meta( $venue_id, '_venue_address', true );
$city       = get_post_meta( $venue_id, '_venue_city', true );
$state      = get_post_meta( $venue_id, '_venue_state', true );
$country    = get_post_meta( $venue_id, '_venue_country', true );
$zip        = get_post_meta( $venue_id, '_venue_zip', true );

// Build a human-readable address string.
$address_parts = array_filter( [ $address, $city, $state, $zip, $country ] );
$full_address  = implode( ', ', $address_parts );

// Enqueue Leaflet CSS from CDN.
wp_enqueue_style(
	'leaflet',
	'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',
	[],
	'1.9.4'
);

// Enqueue Leaflet JS from CDN.
wp_enqueue_script(
	'leaflet',
	'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',
	[],
	'1.9.4',
	true
);

/* translators: %s: venue name */
$aria_label = sprintf( __( 'Map showing location of %s', 'wordpress-groups' ), $venue_name );

$wrapper_attributes = get_block_wrapper_attributes( [
	'class' => 'wp-block-groups-venue-map',
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div
		class="wp-block-groups-venue-map__container"
		role="img"
		aria-label="<?php echo esc_attr( $aria_label ); ?>"
		data-lat="<?php echo esc_attr( $latitude ); ?>"
		data-lon="<?php echo esc_attr( $longitude ); ?>"
		data-name="<?php echo esc_attr( $venue_name ); ?>"
	></div>

	<?php if ( $full_address || $venue_name ) : ?>
		<div class="wp-block-groups-venue-map__address">
			<?php if ( $venue_name ) : ?>
				<strong class="wp-block-groups-venue-map__venue-name">
					<?php echo esc_html( $venue_name ); ?>
				</strong>
			<?php endif; ?>
			<?php if ( $full_address ) : ?>
				<span class="wp-block-groups-venue-map__venue-address">
					<?php echo esc_html( $full_address ); ?>
				</span>
			<?php endif; ?>
		</div>
	<?php endif; ?>
</div>
