<?php
/**
 * Server-side render for the RSVP List block.
 *
 * Displays attending and waitlisted RSVPs for an event, with avatars,
 * display names, and newcomer badges.
 *
 * @package Groups\Blocks
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content (empty for server-rendered).
 * @var WP_Block $block      Block instance.
 */

defined( 'ABSPATH' ) || exit;

// Determine which event to display: explicit attribute or current post context.
$event_id = ! empty( $attributes['eventId'] )
	? (int) $attributes['eventId']
	: ( $block->context['postId'] ?? 0 );

if ( ! $event_id ) {
	return;
}

$event = get_post( $event_id );

if ( ! $event || 'event' !== $event->post_type ) {
	return;
}

// Query attending RSVPs (comments with type 'rsvp' and _rsvp_status meta).
$attending_rsvps = get_comments( [
	'post_id'    => $event_id,
	'type'       => 'rsvp',
	'status'     => 'approve',
	'meta_key'   => '_rsvp_status',
	'meta_value' => 'attending',
	'orderby'    => 'comment_date',
	'order'      => 'ASC',
] );

$waitlisted_rsvps = get_comments( [
	'post_id'    => $event_id,
	'type'       => 'rsvp',
	'status'     => 'approve',
	'meta_key'   => '_rsvp_status',
	'meta_value' => 'waitlisted',
	'orderby'    => 'comment_date',
	'order'      => 'ASC',
] );

$attending_count  = count( $attending_rsvps );
$waitlisted_count = count( $waitlisted_rsvps );

// Nothing to display if no RSVPs at all.
if ( 0 === $attending_count && 0 === $waitlisted_count ) {
	$wrapper_attributes = get_block_wrapper_attributes( [
		'class' => 'wp-block-groups-rsvp-list',
	] );
	printf(
		'<div %s><p class="wp-block-groups-rsvp-list__empty">%s</p></div>',
		$wrapper_attributes, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes().
		esc_html__( 'No RSVPs yet.', 'wordpress-groups' )
	);
	return;
}

/**
 * Render a single RSVP card.
 *
 * @param WP_Comment $rsvp       The RSVP comment object.
 * @param string     $block_name Base block class name.
 */
$render_rsvp_card = function ( WP_Comment $rsvp, string $block_name ) {
	$is_newcomer  = (bool) get_comment_meta( $rsvp->comment_ID, '_rsvp_is_first_event', true );
	$display_name = '';
	$avatar       = '';

	if ( $rsvp->user_id ) {
		$user = get_userdata( $rsvp->user_id );
		if ( $user ) {
			$display_name = $user->display_name;
			$avatar       = get_avatar( $user->ID, 48, '', $user->display_name );
		}
	}

	// Fall back to comment author name if no linked user.
	if ( ! $display_name ) {
		$display_name = $rsvp->comment_author ?: __( 'Anonymous', 'wordpress-groups' );
		$avatar       = get_avatar( $rsvp->comment_author_email, 48, '', $display_name );
	}

	$card_classes = $block_name . '__card';
	if ( $is_newcomer ) {
		$card_classes .= ' ' . $block_name . '__card--newcomer';
	}
	?>
	<li class="<?php echo esc_attr( $card_classes ); ?>">
		<div class="<?php echo esc_attr( $block_name ); ?>__avatar">
			<?php
			// get_avatar() returns an escaped img tag.
			echo $avatar; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- get_avatar() output is pre-escaped.
			?>
		</div>
		<div class="<?php echo esc_attr( $block_name ); ?>__info">
			<span class="<?php echo esc_attr( $block_name ); ?>__name"><?php echo esc_html( $display_name ); ?></span>
			<?php if ( $is_newcomer ) : ?>
				<span class="<?php echo esc_attr( $block_name ); ?>__badge" aria-label="<?php esc_attr_e( 'First-time attendee', 'wordpress-groups' ); ?>">
					<?php esc_html_e( 'Newcomer', 'wordpress-groups' ); ?>
				</span>
			<?php endif; ?>
		</div>
	</li>
	<?php
};

$wrapper_attributes = get_block_wrapper_attributes( [
	'class' => 'wp-block-groups-rsvp-list',
] );
?>

<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="wp-block-groups-rsvp-list__summary" aria-live="polite">
		<span class="wp-block-groups-rsvp-list__count">
			<?php
			$summary_parts = [];

			$summary_parts[] = sprintf(
				/* translators: %d: Number of attendees. */
				_n( '%d attending', '%d attending', $attending_count, 'wordpress-groups' ),
				$attending_count
			);

			if ( $waitlisted_count > 0 ) {
				$summary_parts[] = sprintf(
					/* translators: %d: Number of people on waitlist. */
					_n( '%d waitlisted', '%d waitlisted', $waitlisted_count, 'wordpress-groups' ),
					$waitlisted_count
				);
			}

			echo esc_html( implode( ', ', $summary_parts ) );
			?>
		</span>
	</div>

	<?php if ( $attending_count > 0 ) : ?>
		<div class="wp-block-groups-rsvp-list__section" role="region" aria-label="<?php esc_attr_e( 'Attending', 'wordpress-groups' ); ?>">
			<h3 class="wp-block-groups-rsvp-list__heading"><?php esc_html_e( 'Attending', 'wordpress-groups' ); ?></h3>
			<ul class="wp-block-groups-rsvp-list__grid" role="list">
				<?php
				foreach ( $attending_rsvps as $rsvp ) {
					$render_rsvp_card( $rsvp, 'wp-block-groups-rsvp-list' );
				}
				?>
			</ul>
		</div>
	<?php endif; ?>

	<?php if ( $waitlisted_count > 0 ) : ?>
		<div class="wp-block-groups-rsvp-list__section wp-block-groups-rsvp-list__section--waitlisted" role="region" aria-label="<?php esc_attr_e( 'Waitlisted', 'wordpress-groups' ); ?>">
			<h3 class="wp-block-groups-rsvp-list__heading"><?php esc_html_e( 'Waitlisted', 'wordpress-groups' ); ?></h3>
			<ul class="wp-block-groups-rsvp-list__grid" role="list">
				<?php
				foreach ( $waitlisted_rsvps as $rsvp ) {
					$render_rsvp_card( $rsvp, 'wp-block-groups-rsvp-list' );
				}
				?>
			</ul>
		</div>
	<?php endif; ?>
</div>
